apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pact-broker
  namespace: openshift-gitops
spec:
  destination:
    namespace: pact-broker
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
       - name: secrets.values.pactBrokerAdminPassword
         value: "admin"
    chart: pact-broker
    repoURL: https://redhat-cop.github.io/helm-charts
    targetRevision: 0.0.8
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
