apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-env-appset
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/RedHat-EMEA-SSA-Team/ns-apps
      revision: appsets
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: appset-apps-project
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/RedHat-EMEA-SSA-Team/ns-apps
        targetRevision: appsets
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
